import type { Metadata } from "next";
import { Poppins, Lora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../context/ThemeContext";
import { TranslationProvider } from "@/context/useTranslation";
export const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });
export const lora = Lora({ subsets: ["latin"], weight: ["400", "700"] });

// Create a separate JSON-LD script for location data
export const locationSchema = {
  "@context": "https://schema.org",
  "@type": "Dentist",
  name: "Dr. Heba Hassan Dental Clinic",
  description:
    "Advanced dental care clinic in Abu Dhabi offering comprehensive dental services",
  address: {
    "@type": "PostalAddress",
    streetAddress: "A-20th - Khalifa City - SE",
    addressLocality: "Abu Dhabi",
    addressCountry: "UAE",
  },
  location: {
    "@type": "Place",
    name: "Lotus Holistic Medical Center",
  },
  telephone: "+971559823321",
  url: "https://hebahassan.dental",
};

export const metadata: Metadata = {
  metadataBase: new URL("https://hebahassan.dental"),
  title: "Advanced Dental Care | Dr. Heba Hassan Dental Clinic Abu Dhabi",
  description:
    "Dr. Heba Hassan Mustafa, a renowned specialist oral surgeon with deep knowledge and expertise in dentistry. Offering comprehensive dental care including implants, cosmetic dentistry, and advanced treatments in Khalifa City, Abu Dhabi.",
  keywords: [
    // English Keywords
    "khalifa city",
    "dental clinic abu dhabi",
    "dentist near me",
    "dental implants abu dhabi",
    "cosmetic dentistry",
    "dental veneers",
    "teeth whitening",
    "dental care",
    "wisdom teeth removal",
    "dental surgery",
    "dental clinic khalifa city",
    "best dentist abu dhabi",
    "NEOSS implant system",
    "dental crown",
    "root canal treatment",
    "dental bridges",
    "oral hygiene",
    "dental check-ups",
    "emergency dentist",
    "dental fillings",
    "dental cleaning",
    "gum disease treatment",
    "dental braces",
    "invisible braces",
    "orthodontic treatment",
    "clear aligners",
    "dental x-rays",
    "dental sealants",
    "dental bonding",
    "dental extractions",
    "dental scaling",
    "dental polishing",
    "dental consultation",
    "dental emergency",
    "dental insurance",
    "dental financing",
    "dental technology",
    "dental examination",
    "dental specialists",
    "dental hygienist",
    "dental assistant",
    "dental laboratory",
    "dental materials",
    "dental instruments",
    "dental products",
    "dental services",
    "dental treatments",
    "dental procedures",
    "dental surgery",
    "dental education",
    "dental research",
    "dental publications",
    "dental conferences",
    "dental associations",
    "dental organizations",
    "dental schools",
    "dental colleges",
    "dental universities",
    "dental students",
    "dental graduates",
    "dental professionals",
    "dental experts",
    "dental industry",
    "dental marketing",
    "dental websites",
    "healthcare",
    "oral health",
    "dental health",
    "dental hygiene",
    "dental anatomy",
    "dental physiology",
    "dental clinic khalifa city",
    "dental clinic abu dhabi",
    "dental clinic near me",
    "dental clinic in abu dhabi",
    "dental clinic in khalifa city",
    "dental clinic in uae",
    "dental clinic in khalifa city abu dhabi",
    "dental clinic in abu dhabi uae",
    "dental clinic in khalifa city abu dhabi uae",
    "dental clinic in abu dhabi near me",
    "dental clinic in khalifa city near me",
    "dental clinic in abu dhabi uae near me",
    "dental clinic in khalifa city abu dhabi uae near me",
    "dental clinic in abu dhabi khalifa city",
    "dental clinic in abu dhabi khalifa city uae",
    "dental clinic in abu dhabi khalifa city near me",
    "dental clinic in abu dhabi khalifa city uae near me",
    "dental clinic in khalifa city abu dhabi uae near me",
    "dental clinic in abu dhabi khalifa city uae near me",
    "dental clinic in abu dhabi khalifa city near me",
    "dental clinic in abu dhabi khalifa city uae near me",
    "doctor",
    "dentist",
    "dental",
    "dental care",
    "dental clinic",
    "dental clinic abu dhabi",
    "dental clinic near me",
    "tabib asnan",
    "eiyada asnan abu dhabi",
    "eiyada asnan qariba mini",
    "ziraeat al'asnan abu dhabi",
    "tajmil al'asnan",
    "eiyada asnan",
    "ziraeat al'asnan",
    "tajmil al'asnan",
    "tabiyid al'asnan",
    "taqwim al'asnan",
    "tib al'asnan altajmili",
    "eiyada asnan abu dhabi",
    "afdal tabib asnan",
    "eilaj juthur al'asnan",
    "tarkib al'asnan",
    "jarahat alfam wal'asnan",
    "eiyada asnan madinat khalifa",
    "tanzif al'asnan",
    "eilaj allitha",
    "taqwim al'asnan",
    "ziraeat al'asnan",
    "tabiyid al'asnan",
    "tajmil al'asnan",
    "tarkibat al'asnan",
    "taqwim al'asnan",
    "taqwim al'asnan alshafaf",
    "taqwim al'asnan bidun 'aslak",
    "taqwim al'asnan biallayzr",
    "taqwim al'asnan biallayzr alshafaf",
    "taqwim al'asnan biallayzr bidun 'aslak",
    "taqwim al'asnan biallayzr biallayzr alshafaf",
    "taqwim al'asnan biallayzr biallayzr bidun 'aslak",
    "taqwim al'asnan biallayzr biallayzr biallayzr alshafaf",
    "taqwim al'asnan biallayzr biallayzr biallayzr bidun 'aslak",
    "taqwim al'asnan biallayzr biallayzr biallayzr biallayzr alshafaf",
    "taqwim al'asnan biallayzr biallayzr biallayzr biallayzr bidun 'aslak",
    "taqwim al'asnan biallayzr biallayzr biallayzr biallayzr biallayzr alshafaf",
    "taqwim al'asnan biallayzr biallayzr biallayzr biallayzr bidun 'aslak",
    "taqwim al'asnan biallayzr biallayzr biallayzr biallayzr biallayzr alshafaf",
    "taqwim al'asnan biallayzr biallayzr biallayzr biallayzr bidun 'aslak",
    "heba hassan",
    "heba hassan mostafa",
    "mostafa",
    "hiba",
    "hassen",
    "heba",
    "heba hassan",
    // Arabic Keywords
    "طبيب اسنان",

    "عيادة اسنان ابو ظبي",
    "عيادة اسنان قريبة مني",
    "زراعة الاسنان ابو ظبي",
    "تجميل الاسنان",
    "عيادة اسنان",
    "زراعة الأسنان",
    "تجميل الاسنان",
    "تبييض الاسنان",
    "تقويم الاسنان",
    "طب الأسنان التجميلي",
    "عيادة اسنان ابو ظبي",
    "ابو ظبي",
    "افضل طبيب اسنان",
    "علاج جذور الاسنان",
    "تركيب الاسنان",
    "جراحة الفم والاسنان",
    "عيادة اسنان مدينة خليفة",
    "مدينة خليفة",

    "تنظيف الاسنان",
    "علاج اللثة",
    "تقويم الاسنان",
    "زراعة الاسنان",
    "تبييض الاسنان",
    "تجميل الاسنان",
    "تركيبات الاسنان",
    "تقويم الاسنان",
    "تقويم الاسنان الشفاف",
    "تقويم الاسنان بدون اسلاك",
    "تقويم الاسنان بالليزر",
    "تقويم الاسنان بالليزر الشفاف",
    "تقويم الاسنان بالليزر بدون اسلاك",
    "تقويم الاسنان بالليزر بالليزر الشفاف",
    "تقويم الاسنان بالليزر بالليزر بدون اسلاك",
    "تقويم الاسنان بالليزر بالليزر بالليزر الشفاف",
    "تقويم الاسنان بالليزر بالليزر بالليزر بدون اسلاك",
    "تقويم الاسنان بالليزر بالليزر بالليزر بالليزر الشفاف",
    "تقويم الاسنان بالليزر بالليزر بالليزر بالليزر بدون اسلاك",
    "تقويم الاسنان بالليزر بالليزر بالليزر بالليزر بالليزر الشفاف",
    "تقويم الاسنان بالليزر بالليزر بالليزر بالليزر بدون اسلاك",
    "تقويم الاسنان بالليزر بالليزر بالليزر بالليزر بالليزر الشفاف",
    "تقويم الاسنان بالليزر بالليزر بالليزر بالليزر بدون اسلاك",
  ],
  authors: [
    {
      name: "Dr. Heba Hassan Mustafa",
      url: "https://hebahassan.dental",
    },
  ],
  creator: "Dr. Heba Hassan Mustafa",
  publisher: "Lotus Holistic Medical Center",
  openGraph: {
    type: "website",
    title: "Advanced Dental Care | Dr. Heba Hassan Dental Clinic Abu Dhabi",
    description:
      "Achieve a healthy, beautiful smile with Dr. Heba Hassan! We offer comprehensive dental care, including teeth cleaning, whitening, orthodontics, gum treatments, and dental implants using the latest technology.",
    url: "https://hebahassan.dental",
    siteName: "Dr. Heba Hassan Dental Clinic",
    images: [
      {
        url: "https://hebahassan.dental/Implantology.webp",
        width: 1200,
        height: 630,
        alt: "Dental Implantology",
      },
      {
        url: "https://hebahassan.dental/Cosmetic.webp",
        width: 1200,
        height: 630,
        alt: "Cosmetic Dentistry",
      },
      {
        url: "https://hebahassan.dental/Restorative.webp",
        width: 1200,
        height: 630,
        alt: "Restorative Dentistry",
      },
    ],
    locale: "en_US",
    alternateLocale: "ar_AE",
  },
  twitter: {
    card: "summary_large_image",
    title: "Advanced Dental Care | Dr. Heba Hassan Dental Clinic Abu Dhabi",
    description:
      "Expert dental care in Abu Dhabi offering implants, cosmetic dentistry, and advanced treatments. Visit our modern clinic in Khalifa City.",
    images: ["/"],
  },
  alternates: {
    canonical: "https://hebahassan.dental",
    languages: {
      "en-US": "/en",
      "ar-AE": "/ar",
    },
  },
  verification: {
    google: "googledf0c07f29961a0f4",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  category: "Healthcare",
  other: {
    "script:ld+json": JSON.stringify(locationSchema),
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <ThemeProvider>
          <TranslationProvider>
            <main className="flex-grow">{children}</main>
          </TranslationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
